language: julia
os:
    - osx
    - linux
julia:
    - release
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("CorrelationExpansion"); Pkg.test("CorrelationExpansion"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("CorrelationExpansion")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'cd(Pkg.dir("CorrelationExpansion")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
